"""Automorphism group of Coxeter's integral octonions R (as 8x8 integer matrices in the
Coxeter basis), and lambda_1-neighbours of R at a prime p (the exceptional Brandt setup)."""
import numpy as np, itertools, json, time
from exc_alg import E8, STRUCT, CONJ, COX, oct_to_vec, G
from theta_I import e8_vectors_by_norm

def mul(x, y):            # product of coordinate vectors
    return np.einsum('a,abc,b->c', x, STRUCT, y)
def mulM(X, Y):           # rowwise for arrays
    return np.einsum('ka,abc,kb->kc', X, STRUCT, Y)
def pair(x, y): return int(x @ E8 @ y)
# identity element coordinates:
from exc_alg import ONE as Q1, ZERO as Q0
ONE = np.array([int(g.re) for g in oct_to_vec((Q1, Q0))], dtype=np.int64)
assert np.array_equal(mul(ONE, ONE), ONE)

UNITS = e8_vectors_by_norm(1)[1]          # 240 units

def hnf_basis(vectors):
    """Hermite normal form basis (rows) of the Z-lattice spanned by integer vectors."""
    from math import gcd
    A = [list(map(int, v)) for v in vectors]
    A = [r for r in A if any(r)]
    m = 8
    basis = []
    col = 0
    rows = A
    while rows and col < m:
        rows = [r for r in rows if any(r)]
        piv = [r for r in rows if r[col] != 0]
        if not piv:
            col += 1; continue
        # reduce to a single pivot row by Euclid
        while len(piv) > 1:
            piv.sort(key=lambda r: abs(r[col]))
            p0 = piv[0]
            newp = [p0]
            for r in piv[1:]:
                q = r[col] // p0[col]
                r2 = [a - q*b for a, b in zip(r, p0)]
                if r2[col] != 0: newp.append(r2)
                else: rows.append(r2)
            piv = newp
            rows = [r for r in rows if r[col] == 0]
        p0 = piv[0]
        if p0[col] < 0: p0 = [-a for a in p0]
        basis.append(p0)
        rows = [r for r in rows if r is not p0 and r[col] == 0]
        col += 1
    # reduce above pivots
    B = [list(r) for r in basis]
    for i in range(len(B)):
        c = next(k for k in range(m) if B[i][k] != 0)
        for j in range(i):
            q = B[j][c] // B[i][c]
            B[j] = [a - q*b for a, b in zip(B[j], B[i])]
    return tuple(tuple(r) for r in B)

def algebra_generated(gens):
    """Z-algebra (with 1) generated by the given coordinate vectors, as HNF basis."""
    span = [ONE] + [np.array(g) for g in gens]
    cur = hnf_basis(span)
    while True:
        vecs = [np.array(r) for r in cur]
        prods = [mul(a, b) for a in vecs for b in vecs]
        new = hnf_basis(vecs + prods)
        if new == cur: return cur
        cur = new

def is_full(basis):
    M = np.array(basis, dtype=float)
    return len(basis) == 8 and abs(round(np.linalg.det(M))) == 1

if __name__ == "__main__":
    t0 = time.time()
    gens = None
    for g1, g2, g3 in itertools.combinations(range(240), 3):
        b = algebra_generated([UNITS[g1], UNITS[g2], UNITS[g3]])
        if is_full(b): gens = (g1, g2, g3); break
    print("generating triple of units:", gens, f"[{time.time()-t0:.1f}s]")
    GENS = [UNITS[i] for i in gens]
    def wval(w, gs):
        v = ONE
        for i in w: v = mul(v, gs[i])
        return v
    L = []
    for length in range(1, 5):
        for w in itertools.product([0, 1, 2], repeat=length):
            L.append(w)
    chosen, vecs = [()], [ONE]
    for w in L:
        v = wval(w, GENS)
        if len(vecs) < 8 and len(hnf_basis(vecs + [v])) > len(vecs):
            chosen.append(w); vecs.append(v)
    B = np.array(vecs, dtype=np.int64)
    assert abs(round(np.linalg.det(B.astype(float)))) == 1, np.linalg.det(B)
    Binv = np.round(np.linalg.inv(B.astype(float))).astype(np.int64)
    assert np.array_equal(B @ Binv, np.eye(8, dtype=np.int64))
    print("basis words:", chosen)
    tr = [pair(g, ONE) for g in GENS]
    P = [[pair(GENS[i], GENS[j]) for j in range(3)] for i in range(3)]
    U = UNITS
    trU = U @ E8 @ ONE
    I8 = np.eye(8, dtype=np.int64)
    # precompute all basis products for the multiplicativity check
    PROD = np.array([[mul(I8[a], I8[b]) for b in range(8)] for a in range(8)])   # (8,8,8)
    auts = []
    c1 = U[trU == tr[0]]
    for f1 in c1:
        c2 = U[(trU == tr[1]) & ((U @ E8 @ f1) == P[0][1])]
        for f2 in c2:
            c3 = U[(trU == tr[2]) & ((U @ E8 @ f1) == P[0][2]) & ((U @ E8 @ f2) == P[1][2])]
            for f3 in c3:
                fs = [f1, f2, f3]
                Bimg = np.array([wval(w, fs) for w in chosen], dtype=np.int64)
                M = Binv @ Bimg
                if not np.array_equal(B @ M, Bimg): continue
                # multiplicativity: (e_a e_b) M == (e_a M)(e_b M)
                lhs = np.einsum('abc,cd->abd', PROD, M)
                rhs = np.array([[mul(M[a], M[b]) for b in range(8)] for a in range(8)])
                if np.array_equal(lhs, rhs) and abs(round(np.linalg.det(M.astype(float)))) == 1:
                    auts.append(M)
    print("automorphisms found:", len(auts), f"[{time.time()-t0:.1f}s]")
    np.save('gamma_G2Z.npy', np.array(auts, dtype=np.int64))
    np.save('gens_words.npy', np.array(gens))
